// Code generated by MockGen. DO NOT EDIT.
// Source: collector.go

// Package collector is a generated GoMock package.
package collector

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockICollector is a mock of ICollector interface
type MockICollector struct {
	ctrl     *gomock.Controller
	recorder *MockICollectorMockRecorder
}

// MockICollectorMockRecorder is the mock recorder for MockICollector
type MockICollectorMockRecorder struct {
	mock *MockICollector
}

// NewMockICollector creates a new mock instance
func NewMockICollector(ctrl *gomock.Controller) *MockICollector {
	mock := &MockICollector{ctrl: ctrl}
	mock.recorder = &MockICollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockICollector) EXPECT() *MockICollectorMockRecorder {
	return m.recorder
}

// Collect mocks base method
func (m *MockICollector) Collect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Collect indicates an expected call of Collect
func (mr *MockICollectorMockRecorder) Collect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockICollector)(nil).Collect))
}

// MockIRepository is a mock of IRepository interface
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// SourceID mocks base method
func (m *MockIRepository) SourceID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SourceID indicates an expected call of SourceID
func (mr *MockIRepositoryMockRecorder) SourceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceID", reflect.TypeOf((*MockIRepository)(nil).SourceID))
}

// Add mocks base method
func (m *MockIRepository) Add(arg0 []CollectLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockIRepositoryMockRecorder) Add(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockIRepository)(nil).Add), arg0)
}

// MockTimeInterface is a mock of TimeInterface interface
type MockTimeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTimeInterfaceMockRecorder
}

// MockTimeInterfaceMockRecorder is the mock recorder for MockTimeInterface
type MockTimeInterfaceMockRecorder struct {
	mock *MockTimeInterface
}

// NewMockTimeInterface creates a new mock instance
func NewMockTimeInterface(ctrl *gomock.Controller) *MockTimeInterface {
	mock := &MockTimeInterface{ctrl: ctrl}
	mock.recorder = &MockTimeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTimeInterface) EXPECT() *MockTimeInterfaceMockRecorder {
	return m.recorder
}

// Now mocks base method
func (m *MockTimeInterface) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now
func (mr *MockTimeInterfaceMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimeInterface)(nil).Now))
}

// MockIFetcher is a mock of IFetcher interface
type MockIFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockIFetcherMockRecorder
}

// MockIFetcherMockRecorder is the mock recorder for MockIFetcher
type MockIFetcherMockRecorder struct {
	mock *MockIFetcher
}

// NewMockIFetcher creates a new mock instance
func NewMockIFetcher(ctrl *gomock.Controller) *MockIFetcher {
	mock := &MockIFetcher{ctrl: ctrl}
	mock.recorder = &MockIFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIFetcher) EXPECT() *MockIFetcherMockRecorder {
	return m.recorder
}

// fetch mocks base method
func (m *MockIFetcher) fetch(deviceID string) ([]CollectLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "fetch", deviceID)
	ret0, _ := ret[0].([]CollectLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// fetch indicates an expected call of fetch
func (mr *MockIFetcherMockRecorder) fetch(deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "fetch", reflect.TypeOf((*MockIFetcher)(nil).fetch), deviceID)
}

// MocknoDevice is a mock of noDevice interface
type MocknoDevice struct {
	ctrl     *gomock.Controller
	recorder *MocknoDeviceMockRecorder
}

// MocknoDeviceMockRecorder is the mock recorder for MocknoDevice
type MocknoDeviceMockRecorder struct {
	mock *MocknoDevice
}

// NewMocknoDevice creates a new mock instance
func NewMocknoDevice(ctrl *gomock.Controller) *MocknoDevice {
	mock := &MocknoDevice{ctrl: ctrl}
	mock.recorder = &MocknoDeviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MocknoDevice) EXPECT() *MocknoDeviceMockRecorder {
	return m.recorder
}

// noDevice mocks base method
func (m *MocknoDevice) noDevice() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "noDevice")
	ret0, _ := ret[0].(bool)
	return ret0
}

// noDevice indicates an expected call of noDevice
func (mr *MocknoDeviceMockRecorder) noDevice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "noDevice", reflect.TypeOf((*MocknoDevice)(nil).noDevice))
}
