name: Test

on: 
  push:
    branches: '**'
    path-ignore: README.md

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit test
        run: make test
      - name: Build the stack
        env:
          GCP_PROJECT: test
          NATURE_REMO_ACCESS_TOKEN: ${{ secrets.NATURE_REMO_ACCESS_TOKEN }}
          FIRESTORE_DOC_PATH: test/test
        run: docker-compose up -d
      - name: Integration Test
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8812
          FIRESTORE_DOC_PATH: test/test
          GCP_PROJECT: test
        run: make integration_test
      - name: E2E Test
        env:
          NATURE_REMO_DEVICE_ID: ${{ secrets.NATURE_REMO_DEVICE_ID }}
        run: make e2e_test

