name: Test

on: 
  push:
    branches: '**'
    paths-ignore: 
    - 'README.md'
    - 'cloudbuild.yaml'

jobs:
  backend_test:
    name: Backend Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit test
        run: make test
      - name: Build the stack
        env:
          GCP_PROJECT: test
          NATURE_REMO_ACCESS_TOKEN: ${{ secrets.NATURE_REMO_ACCESS_TOKEN }}
          FIRESTORE_ROOT_PATH: test
        run: docker-compose up -d
      - name: Integration Test
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8812
          FIRESTORE_ROOT_PATH: test
          GCP_PROJECT: test
        run: make integration_test
      - name: E2E Test
        env:
          NATURE_REMO_DEVICE_ID: ${{ secrets.NATURE_REMO_DEVICE_ID }}
          FIRESTORE_EMULATOR_HOST: localhost:8812
          FIRESTORE_ROOT_PATH: test
          GCP_PROJECT: test
        run: make e2e_test
  frontend_test:
    name: Frontend Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cd frontend; npm install; npm run test
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1
      - name: E2E Test
        run: cd frontend; npm install; npm run test:e2e-ci

