name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit test
        run: make test
      - name: Build the stack
        run: docker-compose up -d
      - name: Integration test
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8812
          FIRESTORE_DOC_PATH: test/test
          GCP_PROJECT: test
        run: make integration_test
